# Generated by Django 5.2.5 on 2025-09-02 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('contenu', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('publie_le', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Actualite',
            },
        ),
    ]
