# Generated by Django 5.2.5 on 2025-09-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='type',
            field=models.CharField(blank=True, db_column='type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
