# Generated by Django 5.2.5 on 2025-09-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_actualite_type_alter_actualite_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualite',
            options={'managed': False},
        ),
    ]
