# Generated by Django 5.2.5 on 2025-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('nb_inscrits', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Evenement',
            },
        ),
    ]
