# Generated by Django 5.2.5 on 2025-09-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='photo_url',
            field=models.CharField(blank=True, db_column='photo_url', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='type',
            field=models.CharField(db_column='type', default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nb_inscrits',
            field=models.IntegerField(db_column='nb_inscrits', default=0),
        ),
    ]
