# Generated by Django 5.2.5 on 2025-09-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_evenement_photo_url_evenement_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'managed': False},
        ),
    ]
