# Generated by Django 5.2.5 on 2025-09-02 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('dernier_login', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('maj_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startups.startup')),
            ],
            options={
                'db_table': 'Utilisateurs',
            },
        ),
    ]
