# Generated by Django 5.2.5 on 2025-09-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('startup', 'Startup')], db_column='role', default='startup', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
