# Generated by Django 5.2.5 on 2025-09-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_role_delete_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False},
        ),
    ]
