# Generated by Django 5.2.5 on 2025-09-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilisateur',
            table='users',
        ),
    ]
