# Generated by Django 5.2.5 on 2025-09-02 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1024)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('proprietaire_type', models.CharField(max_length=50)),
                ('proprietaire_id', models.IntegerField()),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Fichier',
            },
        ),
    ]
