# Generated by Django 5.2.5 on 2025-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('lien', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'Opportunites',
            },
        ),
    ]
