# Generated by Django 5.2.5 on 2025-09-02 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(max_length=100)),
                ('cible_type', models.CharField(max_length=100)),
                ('cible_id', models.IntegerField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
    ]
