# Generated by Django 5.2.5 on 2025-09-03 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='API JEB', max_length=255)),
                ('remote_id', models.CharField(max_length=255)),
                ('local_id', models.IntegerField()),
                ('cible_type', models.CharField(max_length=100)),
                ('dernier_sync', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload_brut', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_api',
            },
        ),
    ]
