# Generated by Django 5.2.5 on 2025-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description_courte', models.CharField(blank=True, max_length=255, null=True)),
                ('description_longue', models.TextField(blank=True, null=True)),
                ('secteur', models.CharField(blank=True, max_length=100, null=True)),
                ('stade', models.CharField(blank=True, choices=[('idee', 'Idée'), ('seed', 'Seed'), ('croissance', 'Croissance')], max_length=50, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('site_web', models.CharField(blank=True, max_length=1024, null=True)),
                ('reseaux_sociaux', models.JSONField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_tel', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_incub', models.DateField(blank=True, null=True)),
                ('nb_pers', models.IntegerField(default=0)),
                ('chiffre_aff', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cree_le', models.DateTimeField()),
                ('maj_le', models.DateTimeField()),
            ],
            options={
                'db_table': 'Startup',
            },
        ),
    ]
