# Generated by Django 5.2.5 on 2025-09-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_investor_partner_alter_startup_cree_par_founder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'managed': False},
        ),
    ]
