# Generated by Django 5.2.5 on 2025-09-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_alter_startup_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='startup',
            table='startups',
        ),
    ]
